name:                accel
version:             0.1.0.0
github:              "githubuser/accel"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/accel#readme>

dependencies:
- accelerate                      >= 1.2.0.0 && < 1.3
- accelerate-llvm-ptx
- accelerate-io
- ansi-wl-pprint
- base                            >= 4.7 && < 5
- criterion                       >= 1.1
- containers
- colour-accelerate               == 0.3.0.0
- directory                       >= 1.1
- fclabels
- gloss                           >= 1.7
- gloss-accelerate                == 2.0.0.1
- linear                          >= 1.1
- mwc-random                      >= 0.8
- process                         >= 1.0
- template-haskell                >= 2.2
- vector
- HUnit                           >= 1.2
- QuickCheck                      >= 2.7
- test-framework                  >= 0.5
- test-framework-hunit            >= 0.3
- test-framework-quickcheck2      >= 0.2
- aeson                           >= 0.8
- bytestring                      >= 0.10
- HTTP                            >= 4000.2
- http-types                      >= 0.8
- network                         >= 2.5
- statistics                      >= 0.13
- text                            >= 0.11
- time                            >= 1.4

library:
  source-dirs: src

executables:
  accel-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accel

tests:
  accel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accel
